"""
Django settings for uploadappointments project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Facility MySQL passwords are encrypted with a key derived from SECRET_KEY when
# FIELD_ENCRYPTION_KEY is unset, so changing this value invalidates them.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-xa+%)g3*u)$%nr3l$trs+x##wy(1cdck5+e7#g2n+b*)l=1t)g',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'upload',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves STATIC_ROOT under gunicorn, so DEBUG can be False in production
    # without the admin losing its stylesheets.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uploadappointments.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uploadappointments.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# OpenMRS is not a Django database alias: each facility is a separate KenyaEMR
# container reached through upload.openmrs, which opens a MySQL connection per
# facility. See OPENMRS_DB_* below for the single-facility connection.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Upload workers write progress concurrently; without this they hit
            # "database is locked" instead of waiting their turn.
            'timeout': 20,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# OpenMRS connection used in single-facility mode. In multi-facility mode these
# are ignored and each Facility row supplies its own connection details.
OPENMRS_DB_NAME = os.environ.get('OPENMRS_DB_NAME', '')
OPENMRS_DB_USER = os.environ.get('OPENMRS_DB_USER', '')
OPENMRS_DB_PASSWORD = os.environ.get('OPENMRS_DB_PASSWORD', '')
OPENMRS_DB_HOST = os.environ.get('OPENMRS_DB_HOST', '')
OPENMRS_DB_PORT = os.environ.get('OPENMRS_DB_PORT', '3306')
OPENMRS_DB_LABEL = os.environ.get('OPENMRS_DB_LABEL', 'Local facility')

# API Configuration
CHQI_API_BASE_URL = os.environ.get('CHQI_API_BASE_URL', '')
CHQI_API_USERNAME = os.environ.get('CHQI_API_USERNAME', '')
CHQI_API_PASSWORD = os.environ.get('CHQI_API_PASSWORD', '')

# Upload behaviour
UPLOAD_BATCH_SIZE = int(os.environ.get('UPLOAD_BATCH_SIZE', '10'))
# The central API is the only shared bottleneck (each facility has its own
# MySQL), so this is the one number to tune. Conservative until its rate limit
# is known: 100 facilities at ~2 minutes each finishes in roughly 40 minutes.
MULTI_FACILITY_WORKERS = int(os.environ.get('MULTI_FACILITY_WORKERS', '5'))
# A run whose heartbeat goes quiet for this long is assumed dead.
UPLOAD_STALE_MINUTES = int(os.environ.get('UPLOAD_STALE_MINUTES', '20'))

# Encrypts facility MySQL passwords at rest. Falls back to SECRET_KEY when unset;
# rotating whichever is in use means re-entering every facility password.
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
