# Generated by Django 6.0.4 on 2026-04-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='batches_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='batches_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], max_length=15),
        ),
    ]
