# Generated by Django 4.2.16 on 2026-07-10 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0002_uploadlog_batches_completed_uploadlog_batches_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_facility_enabled', models.BooleanField(default=False, help_text='When enabled, the cron job uploads every active facility instead of the environment-configured one.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this facility in the UI. The name and MFL code sent upstream come from the OpenMRS data itself, not from this field.', max_length=200, unique=True)),
                ('host', models.CharField(help_text='Hostname, container/service name, or IP address of the MySQL server.', max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('database_name', models.CharField(default='openmrs', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('mfl_code', models.CharField(blank=True, default='', max_length=20)),
                ('mfl_facility_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='facility_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UploadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('mode', models.CharField(choices=[('single', 'Single Facility'), ('multi', 'Multi Facility')], default='single', max_length=10)),
                ('triggered_by', models.CharField(choices=[('cron', 'Cron Job'), ('manual', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('facilities_total', models.IntegerField(default=0)),
                ('facilities_completed', models.IntegerField(default=0)),
                ('facilities_failed', models.IntegerField(default=0)),
                ('records_uploaded', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='upload.uploadrun')),
                ('triggered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(condition=models.Q(('mfl_code', ''), _negated=True), fields=('mfl_code',), name='unique_non_blank_mfl_code'),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='upload.facility'),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='upload.uploadrun'),
        ),
    ]
