# Generated by Django 4.2.16 on 2026-08-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_appsettings_facility_uploadlog_facility_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='initial_backfill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='initial_backfill_done',
            field=models.BooleanField(default=False, help_text='Whether the one-off upload of all pending appointments has run.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='initial_backfill_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='upload.uploadrun'),
        ),
        migrations.AddField(
            model_name='facility',
            name='initial_backfill_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadrun',
            name='is_backfill',
            field=models.BooleanField(default=False),
        ),
    ]
