# Generated by Django 4.2.16 on 2026-08-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_appsettings_initial_backfill_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this server in the UI.', max_length=200, unique=True)),
                ('host', models.CharField(help_text='Hostname or IP address of the MySQL server holding the tenant schemas.', max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('database_prefix', models.CharField(default='openmrs_', help_text='Databases whose names start with this are treated as facilities. Matched case-insensitively.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_ok', models.BooleanField(blank=True, null=True)),
                ('last_sync_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='multi_tenant_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, the cron job uploads every schema discovered on the configured multi-tenant servers. Takes precedence over multi-facility mode if both are somehow set.'),
        ),
        migrations.AddField(
            model_name='facility',
            name='disabled_by_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadrun',
            name='mode',
            field=models.CharField(choices=[('single', 'Single Facility'), ('multi', 'Multi Facility'), ('tenant', 'Multi Tenant')], default='single', max_length=10),
        ),
        # The field has to exist before a constraint can reference it; the
        # autodetector emitted these the other way round.
        migrations.AddField(
            model_name='facility',
            name='server',
            field=models.ForeignKey(blank=True, help_text='The multi-tenant server this schema was discovered on, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='upload.tenantserver'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(condition=models.Q(('server__isnull', False)), fields=('server', 'database_name'), name='unique_database_per_tenant_server'),
        ),
    ]
