# Generated by Django 5.2 on 2026-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_facility_activated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlog',
            name='patient_updates_uploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadrun',
            name='patient_updates_uploaded',
            field=models.IntegerField(default=0),
        ),
    ]
