# Generated by Django 5.2 on 2026-09-20 18:42

from django.db import migrations, models
from django.db.models import Max


def seed_catch_up_state(apps, schema_editor):
    """Give an existing deployment the watermarks its history already implies.

    Without this, the first `--due-only` tick on a deployment that has been
    uploading for months would find every watermark empty and read that as "never
    uploaded" — and re-send every pending appointment for every facility. The
    upload history already says how far each of them got: the latest `date_to`
    among its successful logs is, by definition, the last day whose bookings
    reached the platform. Backfill logs carry the day they ran as their date_to,
    so a deployment whose only success was the initial load is covered too.
    """
    UploadLog = apps.get_model('upload', 'UploadLog')
    Facility = apps.get_model('upload', 'Facility')
    AppSettings = apps.get_model('upload', 'AppSettings')

    # A log's own flag is new; before now the run was the only thing that knew.
    UploadLog.objects.filter(run__is_backfill=True).update(is_backfill=True)

    for row in (UploadLog.objects.filter(status='success', facility__isnull=False)
                .values('facility_id').annotate(latest=Max('date_to'))):
        Facility.objects.filter(pk=row['facility_id']).update(
            appointments_synced_through=row['latest'],
        )

    # facility NULL is the environment-configured facility, whose state lives on
    # the settings row — including for logs old enough to predate runs entirely.
    env_latest = (UploadLog.objects.filter(status='success', facility__isnull=True)
                  .aggregate(latest=Max('date_to'))['latest'])
    if env_latest:
        AppSettings.objects.filter(pk=1).update(appointments_synced_through=env_latest)


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_uploadlog_patient_updates_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='appointments_synced_through',
            field=models.DateField(blank=True, help_text='Last day whose bookings reached the platform. The next catch-up window starts here.', null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='appointments_synced_through',
            field=models.DateField(blank=True, help_text='Last day whose bookings reached the platform for this facility. The next catch-up window starts here.', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadlog',
            name='is_backfill',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_catch_up_state, migrations.RunPython.noop),
    ]
